### ISSUE TITLE
How do you run this class with 2-D data ?

### ISSUE THREAD

**Issue by winash12** [RickardSjogren/vptree#8]
If your data is 1-D running the test case is straightforward. I have 2D data in terms of latitude and longitude. Is the class VPTree able to accept 2D data ? The test case is failing.

**Comment by RickardSjogren** [comment]
The VPTree-class expects a sequence of objects, where each object represent the entity you want to query. That is, in the 1D-case the objects is a 1D-point, 2D-case a 2D-point etc. You can use any type of object you like to represent points in any dimension.

In your case you should use a sequence of latitude and longtude-pairs as objects.
